Upgraded to v. 0.98.1103
Does not compile. Build ends at 50% with strange linking errors like
PostbackOptions.cpp:(.text+0x105): undefined reference to `boost::program_options::options_description::options_description(std::string const&, unsigned int, unsigned int)'
in rpostback linking.